### ISSUE TITLE
Cloud instance + related resources state management

### ISSUE THREAD

**Issue by minev-dev** [opencloudtool/opencloudtool#2]
Save instance info to state file when deployed.
Read instance info from state file when destroying.

**Comment by andagaev** [comment]
### ADR: Use state.json for Resource Tracking
#### Objective (Goal)

To implement a mechanism for tracking the state of AWS resources.
Keep information about EC2 instances and related resources (IAM roles, ECR repositories).
Provide human-readable records of the managed resources.
Help tracking for creation, updates, and destroyment.


#### Background (Why You Decided Doing That)

The current implementation of EC2 instance management does not keep the state of created resources. Problems we face:

We cannot clean-up previously created resources because we hadn’t tracked them.
Monitoring is difficult because we do not have records of resource metadata.
Requirements (Acceptance Criteria)
The file must be in JSON format and human-readable.
The file must support adding new resource types and metadata in the future.
The state file must always reflect the current state of resources after any operation.



#### Design

The state.json file will store metadata about EC2 instances and related resources. This file will help us with efficient resource management.

##### Design of state.json:
```
{
  “resources” [
   {
      "resource_type": "ec2_instance",
      “id”: “12345”,
      “public_dns”: “str”,
      “public_ip”: “str”,
      “region”: “str”,
      “ami”: “str”,
      “instance_type: “str”,
      “name”: “str”
    }
  ]
}
```

##### Features:

Creation:
Save metadata of the new created instance to state.json
Deletion:
Remove metadata of the destroyed instances from state.json
File Management:
Create functions for loading, saving json.file

To define what data we want to save to a state file I propose to use struct State with desired fields we want to save to json.state.

In the struct State i would implement these methods:
method load to read current state from the state file
method save to write new data to the state file
method add_instance to append new instance metadata
method remove_instance to delete metadata of the destroyed resource
method get_instance to get data by instance id

Save metadata to state.json right after we get a successful API response when the EC2 instance is created.
Before destroying the instance we retrieve its metadata from the state file to perform proper deletion. Then we remove the deleted resource from the state file and save it.


### PR: https://github.com/opencloudtool/opencloudtool/pull/4

**Comment by minev-dev** [comment]
'''
method add_instance to append new instance metadata
method remove_instance to delete metadata of the destroyed resource
method get_instance to get data by instance id
'''

Doesn't it make the State struct too tightly-coupled with the 'instance'?
What will you do with new resources, like ECR, S3, etc?
